"""
BharatBI — SQL Validator
Validates generated SQL before executing it on the user's database.

Three-layer validation:
1. Parse with sqlglot (catches syntax errors instantly, no DB call needed)
2. EXPLAIN on the actual DB (catches semantic errors: unknown tables/columns)
3. Auto-retry: if validation fails, send error back to LLM for self-correction

This retry loop is key to BharatBI's reliability.
"""

import sqlglot
from typing import Optional


# ── Layer 1: Static parse ─────────────────────────────────────

def parse_sql(sql: str, dialect: str = "postgresql") -> tuple[bool, str]:
    """
    Parses SQL using sqlglot without hitting the database.
    Catches syntax errors, missing commas, wrong keywords, etc.

    Returns:
        (is_valid: bool, error_message: str)
    """
    if not sql or not sql.strip():
        return False, "LLM returned empty SQL"

    # Block dangerous statements
    sql_upper = sql.upper().strip()
    forbidden = ["INSERT ", "UPDATE ", "DELETE ", "DROP ", "TRUNCATE ", "ALTER ", "CREATE ", "GRANT ", "REVOKE "]
    for keyword in forbidden:
        if sql_upper.startswith(keyword) or f" {keyword}" in sql_upper:
            return False, f"Dangerous SQL statement blocked: starts with {keyword.strip()}"

    try:
        parsed = sqlglot.parse(sql, dialect=dialect)
        if not parsed:
            return False, "SQL parsed to empty AST"
        return True, ""
    except sqlglot.errors.ParseError as e:
        return False, f"SQL parse error: {e}"


# ── Layer 2: DB EXPLAIN ───────────────────────────────────────

async def explain_sql(sql: str, connector) -> tuple[bool, str]:
    """
    Runs EXPLAIN on the target database to catch semantic errors
    (unknown tables, column name typos, type mismatches, etc.)

    Returns:
        (is_valid: bool, error_message: str)
    """
    return await connector.validate_sql(sql)


# ── Full validation with retry loop ───────────────────────────

async def validate_and_fix_sql(
    sql: str,
    dialect: str,
    connector,
    llm_provider,
    original_question: str,
    schema_chunks: list[dict],
    max_retries: int = 3,
) -> tuple[str, str]:
    """
    Validates SQL and auto-retries with LLM if it fails.

    Args:
        sql: The SQL generated by the LLM
        dialect: 'postgresql' or 'mysql'
        connector: The BaseConnector for the user's DB
        llm_provider: The BaseLLMProvider to call for fixes
        original_question: The user's original question (for context)
        schema_chunks: The schema context (for re-prompting)
        max_retries: How many times to ask LLM to fix its SQL

    Returns:
        (valid_sql: str, final_error: str)
        If all retries fail, final_error will be non-empty.
    """
    from packages.core.prompt_builder import build_sql_prompt

    current_sql = sql
    last_error = ""

    for attempt in range(max_retries + 1):
        # Layer 1: parse
        is_valid, parse_error = parse_sql(current_sql, dialect)
        if not is_valid:
            last_error = parse_error
        else:
            # Layer 2: EXPLAIN
            is_valid, explain_error = await explain_sql(current_sql, connector)
            if not is_valid:
                last_error = explain_error
            else:
                # Both passed — SQL is valid
                return current_sql, ""

        # If this was the last attempt, give up
        if attempt >= max_retries:
            break

        # Ask LLM to fix the SQL
        error_context = (
            f"SQL that failed:\n{current_sql}\n\n"
            f"Error:\n{last_error}"
        )
        retry_prompt = build_sql_prompt(
            question=original_question,
            schema_chunks=schema_chunks,
            dialect=dialect,
            extra_context=error_context,
        )
        result = await llm_provider.generate_sql(retry_prompt)
        current_sql = result.sql

    return "", last_error